### ISSUE TITLE
undefined method `[]' for false:FalseClass (NoMethodError)

### ISSUE THREAD

**Issue by thob97** [clajiness/qBittorrent-PIA-Port-Forwarder#2]
Im getting the following error when running your code with ruby 2.6.5

Traceback (most recent call last):
        1: from qbt_pia_port_forwarder.rb:170:in `<main>'
qbt_pia_port_forwarder.rb:43:in `get_config': undefined method `[]' for false:FalseClass (NoMethodError)

**Comment by clajiness** [comment]
Hey, sorry. I don't use this tool any longer as I don't pay for PIA. Were you able to get it running since posting this issue?

If not, did you create your initial_config.yml file? If so, which OS are you trying to run this on? What happens when you run `ip route | head -1 | grep tun | awk '{ print $3 }` in terminal?
